project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('wishlist/', include('wishlist.urls')),
    path('', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist, show_wishlist_xml, show_wishlist_json, show_wishlist_ajax, show_item_by_id_xml, show_item_by_id_json, register, login_user, logout_user, add_barang

app_name = 'wishlist'

urlpatterns = [
	path('', show_wishlist, name='show_wishlist'),
	path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
	path('ajax/submit', add_barang, name='add_barang'),
	path('xml/', show_wishlist_xml, name='show_wishlist_xml'),
	path('json/', show_wishlist_json, name='show_wishlist_json'),
	path('xml/<int:id>', show_item_by_id_xml, name='show_item_by_id_xml'),
	path('json/<int:id>', show_item_by_id_json, name='show_item_by_id_json'),
	path('register/', register, name='register'),
	path('login/', login_user, name='login'),
	path('logout/', logout_user, name='logout'),
]

wishlist/models.py
from django.db import models

class BarangWishlist(models.Model):
	nama_barang = models.CharField(max_length=50)
	harga_barang = models.IntegerField()
	deskripsi = models.TextField()

	def __str__(self) -> str:
		return self.nama_barang

wishlist/forms.py
from django import forms
from .models import BarangWishlist

class BarangWishlistForm(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields = ['nama_barang', 'harga_barang', 'deskripsi']

    def __str__(self):
        return ""

wishlist/views.py
import json
from django.shortcuts import render
from wishlist.models import BarangWishlist
from wishlist.forms import BarangWishlistForm
from django.http import HttpResponse, HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.admin.views.decorators import staff_member_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# @login_required(login_url='/wishlist/login/')
def show_wishlist(request):

	data_barang_wishlist = BarangWishlist.objects.all()
	context = {
		'list_barang': data_barang_wishlist,
		'nama': 'Bapak H',
		# 'last_login': request.COOKIES['last_login'],
	}

	return render(request, "wishlist.html", context)

def show_wishlist_xml(request):

	data = BarangWishlist.objects.all()

	return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_wishlist_json(request):

	data = BarangWishlist.objects.all()

	return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_item_by_id_xml(request, id):

	data = BarangWishlist.objects.filter(pk=id)

	return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_item_by_id_json(request, id):

	data = BarangWishlist.objects.filter(pk=id)

	return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
	form = UserCreationForm()

	if request.method == "POST":
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Akun telah berhasil dibuat!')
			return redirect('wishlist:login')
	
	context = {'form':form}
	return render(request, 'register.html', context)

def login_user(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user) # melakukan login terlebih dahulu
			response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
			# response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
			return response
		else:
			messages.info(request, 'Username atau password salah!')
	context = {}
	return render(request, 'login.html', context)

def logout_user(request):
	logout(request)
	response = HttpResponseRedirect(reverse('wishlist:login'))
	# response.delete_cookie('last_login')
	messages.info(request, 'Anda telah berhasil keluar!')
	return response

def show_wishlist_ajax(request):

	context = {
		'nama': 'Bapak H',
	}

	return render(request, "wishlist_ajax.html", context)

@login_required
@staff_member_required
def add_barang(request):
	form = BarangWishlistForm()

	if request.method == "POST":
		form = BarangWishlistForm(json.loads(request.body))
		if form.is_valid():
			form.save()
			return HttpResponse(status=201)
		return HttpResponse(status=400)

	return HttpResponse(status=400)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

templates/base_2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	{% block meta %}
	{% endblock meta %}
</head>

<body>
	{% block content %}
	{% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Masuk • Hans TM @ Lab PBP</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container">

	<h1 class="mt-3 mb-3">Masuk</h1>

	{% if messages %}
	<div class="alert alert-primary mb-3">
		<ul class="mb-0">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	<form method="POST" action="" class="mb-3">
		{% csrf_token %}
		<div class="mb-3">
			<label for="inputUserName" class="form-label">Username</label>
			<input type="text" name="username" id="inputUserName" class="form-control">
		</div>
		<div class="mb-3">
			<label for="inputPassword" class="form-label">Password</label>
			<input type="password" name="password" id="inputPassword" class="form-control">
		</div>
		<button class="btn btn-primary" type="submit">Login</button>
	</form>

	<p>Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat akun</a>.</p>

</div>

{% endblock content %}

wishlist/templates/navbar.html
<nav class="navbar navbar-expand-sm bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'wishlist:show_wishlist' %}">Wishlist <small class="text-muted">Hans TM @ Lab PBP</small></a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSide" aria-controls="navbarSide" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSide">
			<ul class="navbar-nav ms-auto mb-2 mb-sm-0">
				<li class="ml-auto nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						{% if request.user.is_anonymous %}
						Anonim
						{% else %}
						{{ request.user }}
						{% endif %}
					</a>
					<ul class="dropdown-menu dropdown-menu-sm-end">
						{% if request.user.is_anonymous %}
						<li><a class="dropdown-item" href="{% url 'wishlist:login' %}">Masuk</a></li>
						<li><a class="dropdown-item" href="{% url 'wishlist:register' %}">Daftar</a></li>
						{% else %}
						<li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Keluar</a></li>
						{% endif %}
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Pendaftaran • Hans TM @ Lab PBP</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container">

	<h1 class="mt-3 mb-3">Pendaftaran</h1>

	{% if messages %}
	<div class="alert alert-primary mb-3">
		<ul class="mb-0">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	<form method="POST" class="mb-3">
		{% csrf_token %}
		<div class="mb-3">
			<label for="inputUserName" class="form-label">Username</label>
			<input type="text" name="username" id="inputUserName" class="form-control mb-2" required>
			<p class="small">150 karakter atau kurang. Huruf, angka dan @/./+/-/_ saja.</p>
		</div>
		<div class="mb-3">
			<label for="inputPassword" class="form-label">Password</label>
			<input type="password" name="password1" id="inputPassword" class="form-control mb-2" required>
			<ul class="small">
				<li>Password Anda tidak boleh terlalu mirip dengan informasi pribadi Anda yang lain.</li>
				<li>Password Anda harus mengandung setidaknya 8 karakter.</li>
				<li>Password Anda tidak boleh berupa password yang umum digunakan.</li>
				<li>Password Anda tidak boleh sepenuhnya numerik.</li>
			</ul>
		</div>
		<div class="mb-3">
			<label for="inputPasswordConfirm" class="form-label">Konfirmasi password</label>
			<input type="password" name="password2" id="inputPasswordConfirm" class="form-control mb-2" required>
			<p class="small">Masukkan password yang sama seperti sebelumnya, untuk verifikasi.</p>
		</div>
		<button class="btn btn-primary" type="submit">Daftar</button>
	</form>

	<p>Sudah mempunyai akun? <a href="{% url 'wishlist:login' %}">Masuk</a>.</p>

</div>

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block meta %}
<title>Wishlist • Hans TM @ Lab PBP</title>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}

<div class="container">
	<p class="mt-3"><b>Nama:</b> {{ nama }}</p>

	{% if messages %}
	<div class="alert alert-primary mb-3">
		<ul class="mb-0">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>	
	</div>
	{% endif %}

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Nama Barang</th>
				<th>Harga Barang</th>
				<th>Deskripsi</th>
			</tr>	
		</thead>
		{% comment %} Tambahkan data di bawah baris ini {% endcomment %}
		<tbody>
			{% for barang in list_barang %}
			<tr>
				<td>{{barang.nama_barang}}</td>
				<td>{{barang.harga_barang}}</td>
				<td>{{barang.deskripsi}}</td>
			</tr>
			{% endfor %}	
		</tbody>
	</table>

</div>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Wishlist • Hans TM @ Lab PBP</title>
<script>window.CSRF_TOKEN = "{{ csrf_token }}"</script>
<script src="{% static 'js/wishlist_ajax.js' %}" defer></script>
{% endblock meta %}

{% block content %}

<nav class="navbar navbar-expand-sm bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="{% url 'wishlist:show_wishlist' %}">Wishlist <small class="text-muted">Hans TM @ Lab PBP</small></a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSide" aria-controls="navbarSide" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSide">
			<ul class="navbar-nav me-auto mb-2 mb-sm-0">
				{% if request.user.is_staff %}
				<li class="nav-item">
					<a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#addModal">Tambah Barang</a>
				</li>
				{% endif %}
			</ul>
			<ul class="navbar-nav ms-auto mb-2 mb-sm-0">
				<li class="ml-auto nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						{% if request.user.is_anonymous %}
						Anonim
						{% else %}
						{{ request.user }}
						{% endif %}
					</a>
					<ul class="dropdown-menu dropdown-menu-sm-end">
						{% if request.user.is_anonymous %}
						<li><a class="dropdown-item" href="{% url 'wishlist:login' %}">Masuk</a></li>
						<li><a class="dropdown-item" href="{% url 'wishlist:register' %}">Daftar</a></li>
						{% else %}
						<li><a class="dropdown-item" href="{% url 'wishlist:logout' %}">Keluar</a></li>
						{% endif %}
					</ul>
				</li>
			</ul>
		</div>
	</div>
</nav>

<div class="container">
	<p class="mt-3"><b>Nama:</b> {{ nama }}</p>

	{% if messages %}
	<div class="alert alert-primary mb-3">
		<ul class="mb-0">
			{% for message in messages %}
			<li>{{ message }}</li>
			{% endfor %}
		</ul>
	</div>
	{% endif %}

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Nama Barang</th>
				<th>Harga Barang</th>
				<th>Deskripsi</th>
			</tr>
		</thead>
		<tbody></tbody>
	</table>

</div>

<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h1 class="modal-title fs-5" id="addModalLabel">Tambah Barang</h1>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<form id="addForm">
				{% csrf_token %}
				<div class="modal-body">
					<div class="mb-3">
						<label for="namaBarangInput" class="form-label">Nama barang</label>
						<input type="text" class="form-control" id="namaBarangInput">
					</div>
					<div class="mb-3">
						<label for="hargaBarangInput" class="form-label">Harga barang</label>
						<input type="number" class="form-control" id="hargaBarangInput">
					</div>
					<div class="mb-3">
						<label for="deskripsiInput" class="form-label">Deskripsi</label>
						<input type="text" class="form-control" id="deskripsiInput">
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary" id="addModalSubmit">Tambah</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock content %}